version: "3.4"

services:
  backend:
    build: docker/backend
    volumes:
      - ./src/backend:/workspace
    depends_on:
      - search
      - db
    command: "flask run -h 0.0.0.0"
    environment:
      DB_URL: "postgresql://db_user:123456@db:5432/fuckdb"
      FLASK_APP: main.py
      FLASK_ENV: development
    ports:
      - 25088:5000


  test:
    build: docker/backend
    volumes:
      - ./test:/workspace/test
      - ./src:/workspace/src
    depends_on:
      - test_db
      - test_backend
    command: "pytest --tb=native --maxfail=1 /workspace/test"
    environment:
      DB_URL: "postgresql://db_user:123456@test_db:5432/fuckdb"
      url: http://test_backend:5000
      PYTHONPATH: "/workspace/src/backend:/workspace/test"

  test_db:
    image: "postgres"
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "fuckdb"

  test_backend:
    build: docker/backend
    volumes:
      - ./src/backend:/workspace:ro
      - /tmp/tmp_storage:/storage
    depends_on:
      - test_db
    command: "flask run -h 0.0.0.0"
    environment:
      DB_URL: "postgresql://db_user:123456@test_db:5432/fuckdb"
      FLASK_APP: main.py
      FLASK_ENV: development


  search:
    build: docker/backend
    volumes:
      - ./src/xueshu_searcher:/workspace
    command: "python server.py"
    environment: {}
    ports: []

  notebook:
    build: docker/backend
    volumes:
      - ./src/backend:/workspace
    # command: "python main.py"
    command: "jupyter lab --no-browser --bind=0.0.0.0"
    environment: {}
    ports:
      - 25099:8888

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "fuckdb"
    volumes:
      - ./db_storage/db:/var/lib/postgresql/data
    ports:
      - "25068:5432"
  
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es01
    environment:
      - discovery.type=single-node
    volumes:
      - ./db_storage/elastic_search/data0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  ftp:
    image: stilliard/pure-ftpd:latest
    restart: always
    volumes:
      - ./db_storage/ftp:/home/ftpusers
      - ./db_storage/ftpd:/etc/pure-ftpd
    ports:
      - "10021:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "202.120.44.152"
      FTP_USER_NAME: "ftpusers"
      FTP_USER_PASS: "ftpusers"
      FTP_USER_HOME: "/home/ftpusers"
      FTP_PASSIVE_PORTS: "30000:30009"
      FTP_MAX_CONNECTIONS: 10
