version: "3.4"

services:
  backend:
    build: docker/backend
    volumes:
      - ./src/backend:/workspace
    # command: "python main.py"
    command: "flask run -h 0.0.0.0"
    environment:
       FLASK_APP: main.py
       FLASK_ENV: development
    ports:
      - 25088:5000

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "fuckdb"
    volumes:
      - ./datadir:/var/lib/postgresql/data
    ports:
      - "25068:5432"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es01
    environment:
      - discovery.type=single-node
    volumes:
      - ./db_storage/elastic_search/data0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  ftp:
    image: stilliard/pure-ftpd:latest
    restart: always
    volumes:
      - ./db_storage/ftp:/home/ftpusers
      - ./db_storage/ftpd:/etc/pure-ftpd
    ports:
      - "10021:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "202.120.44.152"
      FTP_USER_NAME: "ftpusers"
      FTP_USER_PASS: "ftpusers"
      FTP_USER_HOME: "/home/ftpusers"
      FTP_PASSIVE_PORTS: "30000:30009"
      FTP_MAX_CONNECTIONS: 10
